src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;
use Cocur\Slugify\Slugify;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{

    const HEAT =[
        0 =>'Electric',
        1 =>'Gaz'
    ];

    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $surface = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\Column]
    private ?int $bedrooms = null;

    #[ORM\Column]
    private ?int $floor = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $heat = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $postal_code = null;

    #[ORM\Column]
    private ?bool $sold = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    

    public function  __construct(){
        $this->created_at = new \DateTimeImmutable();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

   

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }


    public function getHeatType():string{
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function isSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(PropertyRepository $repo): Response
    {
       $properties = $repo->findLatest();
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'properties' =>$properties
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;
use App\Entity\Property; 
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\PropertyRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class PropertyController extends AbstractController
{
    #[Route('/property', name: 'app_property')]
    public function index(ManagerRegistry $doctrine,PropertyRepository $repo): Response

    {
        $prop = $repo->findAllVisible();
        dump($prop);
   
        return $this->render('property/index.html.twig', [
            'controller_name' => 'PropertyController',
        ]);
    }



    #[Route('/property/{title}-{id}', name: 'property.show')]

    public function show($title,$id,PropertyRepository $repo) :Response {
        $property = $repo->find($id);
        return $this->render('property/show.html.twig', [
            'property' =>$property, 
            'controller_name' => 'PropertyController',
        ]);

    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{path('app_home')}}">Mon agence</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{path('app_property')}}">Acheter</a>
        </li>
        
      
    </div>
  
</nav>
        {% block body %}
        
        {% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome in home page!{% endblock %}

{% block body %}


<div class="container">
  <h1>Welcome in Home page</h1>
  <p>This is some text.</p>
</div>

<div class="container">
  <h2> Les derniers biens </h2>
  <div class="row flex">

      {% for p in properties %}
        <div class="col-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Special title treatment</h5>
              <a href="{{path('property.show',{id:p.id,title:p.title})}}">{{p.title}}</a>
              <p class="card-text">{{p.city}} {{p.postalCode}}</p>
              <div class="text-primary" style="font-weight :bold;font-size : 2erm;"> {{p.price | number_format(0, '',' ')}} $</div>
            </div>
          </div>
        </div>
   
     
      {% endfor %}
  </div>
</div>

{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} nos biens!{% endblock %}

{% block body %}

<div class="example-wrapper" style="text-align : center">
<h1> Voir tous Nos biens ! </h1>
   </div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} nos biens!{% endblock %}

{% block body %}

<div class="container mt-4" >
    <div class="row">

        <div class="col-md-8">

        </div>
        <div class="col-md-4">
            <h1>{{property.title}}</h1>
            <h2>{{property.rooms}} pièces - {{property.surface}} m2 </h2>
            <div class="text-primary" style="font-size :4rem;font-weight:bold;">{{property.price | number_format(0,'',' ')}}$ </div>
            <a href ="#" class="btn btn-primary">Contacter l'agence</a>
        </div>

    </div>
    {# <nav class="nav nav-tabs" id="tab"></nav> #}
    <p>
    {{property.description |nl2br}}
    </p>

    <div class="row">
        <div class="cold-md-8">
        <h2>Caractéristique </h2>
            <table class="table table-striped">
                <tr>
                    <td> Surface Habitable </td>
                    <td> {{property.surface}}m2</td>
                </tr>
                <tr>
                    <td> Pièces </td>
                    <td> {{property.rooms}}</td>
                </tr>

                <tr>
                    <td> Chambre </td>
                    <td> {{property.bedrooms}}</td>
                </tr>

                <tr>
                    <td> Etage </td>
                    <td> {{property.floor}}</td>
                </tr>

                <tr>
                    <td> Chauffage</td>
                    <td> {{property.heatType}}</td>
                </tr>
            </table>
        </div>
            <div class="col-md-4">
            <h2> Spécificité </h2>
            </div>
    </div>

</div>

{% endblock %}